### ISSUE TITLE
Outfitting/Tailoring - Locks due to Yarn Size

### ISSUE THREAD

**Issue by jayRyan24** [rpherbig/dr-scripts#551]
So, when I began to knit I had left-over yarn that wasn't disposed of, probably due to me stopping the script manually before workorders or whatever it is, had a chance to dispose of left-over yarn. sew would try and knit, but it would tell me I didn't have enough yarn to continue, this wold never resolve itself. To test this, I went ahead and ran the workorders manually, and it locked up. I then removed all yarn and went through the process again and it fixed itself and ran through them flawlessly. 

http://pastebin.com/XKSfbRFm

**Comment by jayRyan24** [comment]
A more extensive log, I don't it was happening because of what I mentioned earlier. 

http://pastebin.com/BTtB6zvY

**Comment by rcuhljr** [comment]
Should be fixed.

**Comment by rpherbig** [comment]
7734e8dccd7a8265de4a24a2f721448fcf512574

Still occuring, there's a bug in the combine logic.

```
[workorders]>get yarn

You get some wool yarn from inside your backpack.

[workorders]>count my yarn

You count out 15 yards of material there.

[workorders]>put my yarn in my backpack

You put your yarn in your backpack.
```

At this point there is one in the backpack.

```
[workorders]>order 13

The attendant says, "You can purchase 100 yards of wool yarn for 625 Kronars.  Just order it again and we'll see it done!"

[workorders]>order 13


[workorders]>put my yarn in my backpack

The attendant takes some coins from you and hands you 100 yards of wool yarn.
You put your yarn in your backpack.
```

Now two in the backpack.

```
[workorders]>get yarn from backpack

You get some wool yarn from inside your backpack.

[workorders]>get yarn from backpack

You get some wool yarn from inside your backpack.

[workorders]>combine yarn with yarn

You combine the spools of thread together.
```

Now zero in the backpack, one in hand.

```
[workorders]>order 13

The attendant says, "You can purchase 100 yards of wool yarn for 625 Kronars.  Just order it again and we'll see it done!"

[workorders]>order 13

The attendant takes some coins from you and hands you 100 yards of wool yarn.

[workorders]>put my yarn in my backpack

You put your yarn in your backpack.
```

Now one in backpack, one in hand.

```
[workorders]>get yarn from backpack

You get some wool yarn from inside your backpack.
```

Zero in backpack, two in hand.

```
[workorders]>get yarn from backpack

What were you referring to?

[workorders]>put my yarn in my backpack

You put your yarn in your backpack.
```

There's the error: it tries to get two from the backpack. That causes it to abort combining and put one away, which means the later get (in sew) "fails".

```
[sew]>get my wool yarn

You are already holding that.
```

Testing a fix now.
