### ISSUE TITLE
CHELSEA OVERLOOK - Needs to be connected to the main map areas.

### ISSUE THREAD

**Issue by Aurayn** [rpherbig/dr-scripts#753]
https://snag.gy/vLb7Hk.jpg

 Needs to be connected to the main map areas.

**Comment by rcuhljr** [comment]
Done.

**Comment by Aurayn** [comment]
Thank you  :)

**Comment by Aurayn** [comment]
hmmmm

[script done]
--- Lich: go2 active.
[go2: error: failed to find a path between your current room (7661) and destination room (2970)]
--- Lich: go2 has exited.

still not linked.. .Etreu said that would be all you needed?

**Comment by rcuhljr** [comment]
I was able to go2 2970 from 1230 and TGSE on two different characters, it's updated.

**Comment by Aurayn** [comment]
hmmm umm duh maybe need to download the maps again?
